src/main/java/org/imixs/muluk/MonitorController.java
/*******************************************************************************
 *  Imixs Workflow Technology
 *  Copyright (C) 2003, 2008 Imixs Software Solutions GmbH,  
 *  http://www.imixs.com
 *  
 *  This program is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU General Public License 
 *  as published by the Free Software Foundation; either version 2 
 *  of the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 *  General Public License for more details.
 *  
 *  You can receive a copy of the GNU General Public
 *  License at http://www.gnu.org/licenses/gpl.html
 *  
 *  Contributors:  
 *  	Imixs Software Solutions GmbH - initial API and implementation
 *  	Ralph Soika
 *  
 *******************************************************************************/
package org.imixs.muluk;

import java.io.Serializable;
import java.nio.file.AccessDeniedException;
import java.util.Date;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.imixs.muluk.xml.XMLConfig;
import org.imixs.muluk.xml.XMLObject;

/**
 * This backing bean provides front end data about the MontorService.
 * 
 * @author rsoika
 * @version 1.0
 */
@Named
@SessionScoped
public class MonitorController implements Serializable {

    private static final long serialVersionUID = 1L;

    private static Logger logger = Logger.getLogger(MonitorController.class.getName());

    @Inject
    MonitorService monitorService;

    public MonitorController() {
        super();

    }

    /**
     * This method start the system setup during deployment
     * 
     * @throws AccessDeniedException
     */
    @PostConstruct
    public void init() {
        logger.info("...started");

        logger.info("app start=" + monitorService.getStarted());

    }

    public Date getStarted() {
        return monitorService.getStarted();
    }

    /**
     * Returns the object availiblity
     * 
     * @return
     */
    public double getAvailability() {
        double pings = getConfig().getObjectPings();
        double errors = getConfig().getObjectErrors();
        double total = pings + errors;
        double result = 0;
        if (total > 0) {
            result = pings / total * 100;
        }
        return result;
    }

    /**
     * Returns the cluster availability
     */
    public double getClusterAvailability() {
        double pings = getConfig().getClusterPings();
        double errors = getConfig().getClusterErrors();
        double total = pings + errors;
        double result = 0;
        if (total > 0) {
            result = pings / total * 100;
        }
        return result;
    }

    /**
     * Returns the objects.
     * 
     * @return
     */
    public XMLConfig getConfig() {
        return monitorService.getConfig();
    }

    public String getName() {
        return monitorService.getConfig().getCluster().getName();
    }

    /**
     * Returns the objects.
     * 
     * @return
     */
    public XMLObject[] getObjects() {
        return monitorService.getConfig().getMonitor().getObject();
    }

    public int getObjectsTotal() {
        return monitorService.getConfig().getMonitor().getObject().length;
    }

    public int getObjectsUp() {
        int result = 0;
        XMLObject[] objects = monitorService.getConfig().getMonitor().getObject();
        for (XMLObject obj : objects) {
            if ("OK".equals(obj.getStatus())) {
                result++;
            }
        }
        return result;
    }

    public String getUptime() {

        long different = System.currentTimeMillis() - monitorService.getStarted().getTime();
        long secondsInMilli = 1000;
        long minutesInMilli = secondsInMilli * 60;
        long hoursInMilli = minutesInMilli * 60;
        long daysInMilli = hoursInMilli * 24;
        long elapsedDays = different / daysInMilli;
        different = different % daysInMilli;

        long elapsedHours = different / hoursInMilli;
        different = different % hoursInMilli;

        long elapsedMinutes = different / minutesInMilli;
        different = different % minutesInMilli;

        long elapsedSeconds = different / secondsInMilli;

        String uptime = "";

        if (elapsedDays > 0) {
            uptime = uptime + elapsedDays + " days, ";
        }
        if (elapsedHours > 0) {
            uptime = uptime + elapsedHours + " hours, ";
        }

        if (elapsedMinutes > 0) {
            uptime = uptime + elapsedMinutes + " minutes, ";
        }

        uptime = uptime + elapsedSeconds + " seconds";

        return uptime;

    }

    public int getClusterSize() {
        return monitorService.getConfig().getCluster().getNode().length;
    }

    public int getClusterUp() {
        int result = 0;
        for (XMLObject obj : monitorService.getConfig().getCluster().getNode()) {
            if (MonitorService.STATUS_OK.equalsIgnoreCase(obj.getStatus())) {
                result++;
            }
        }
        return result;
    }

    public XMLObject[] getClusterNodes() {
        return monitorService.getConfig().getCluster().getNode();
    }

}

src/main/webapp/index.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs"
	template="/layout/template.xhtml">

	<ui:define name="content">
		<div class="container-box">
			<div style="flex-grow: 1;">
				<div class="container-panel" style="min-height:300px;"  data-title="Cluster Monitor">
					<p>Started: #{monitorController.started}</p>
					<h2 class="green">Up Time: #{monitorController.uptime}</h2>
				
					<table id="imixsdatatable" class="imixsdatatable"
						style="width: 100%;">
						<thead>
							<tr>
								<th>Cluster Nodes</th>
								<th>Status</th>
								<th>Last Success</th>
								<th>Last Failure</th>
							</tr>
						</thead>
						<tbody>
							<ui:param name="objects"
								value="#{monitorController.clusterNodes}"></ui:param>

							<ui:repeat var="obj" value="#{objects}">
								<tr style="#{'OK' eq obj.status?'':'color:red;'}">
									<td>
										<ui:fragment rendered="#{obj.getTarget().startsWith('http')}">
											<a href="#{obj.getTarget()}" target="_blank">#{obj.getTarget()}</a>
										</ui:fragment>
										<ui:fragment rendered="#{!obj.getTarget().startsWith('http')}">
											#{obj.getTarget()}
										</ui:fragment>
									</td>
									<td>#{obj.status}</td>
									<td>#{obj.lastSuccess}</td>
									<td>#{obj.lastFailure}</td>
								</tr>
							</ui:repeat>
						</tbody>
					</table>

				</div>
			</div>
			
			
			<div>
			
				<div class="container-panel"  data-title="Cluster Status">
					<p>All Cluster Nodes:</p>
					<h3 class="green">Availability = <h:outputText value="#{monitorController.clusterAvailability}">
							<f:convertNumber type="number" groupingUsed="true"
								maxFractionDigits="4" minFractionDigits="1" />
						</h:outputText> %</h3>
					<h3 class="red">Total Errors = #{monitorController.config.clusterErrors}</h3>
				</div>
				
				<div class="container-panel"  data-title="Object Status">
					<p>All Objects:</p>
					<h3 class="green">
						Availability =
						<h:outputText value="#{monitorController.availability}">
							<f:convertNumber type="number" groupingUsed="true"
								maxFractionDigits="4" minFractionDigits="1" />
						</h:outputText>
						%
					</h3>
					<h3 class="red">Total Errors =
						#{monitorController.config.objectErrors}</h3>
				</div>
			</div>
			<div>
				<div class="container-panel #{(monitorController.clusterSize-monitorController.clusterUp) gt 0?'red':'green'}" data-title="Cluster" >
					<p>Nodes Watching:</p>
					<h2 class="">#{monitorController.clusterUp}/#{monitorController.clusterSize}
						Monitors Up</h2>
				</div>

				<div class="container-panel #{(monitorController.objectsTotal-monitorController.objectsUp) gt 0?'red':'green'}"  data-title="Objects">
					<p>Objects Watching:</p>
					<h2>#{monitorController.objectsUp}/#{monitorController.objectsTotal} Objects Up</h2>
				</div>
			</div>
		</div>



		<div class="container-box">

			<div class="container-panel" style="width: 100%;"  data-title="Object Monitor">
				<table id="imixsdatatable" class="imixsdatatable"
					style="width: 100%;">
					<thead>
						<tr>
							<th>Target</th>
							<th>Type</th>
							<th>Interval</th>
							<th>Pattern</th>
							<th>Status</th>
							<th>Last Success</th>
							<th>Last Failure</th>
						</tr>
					</thead>
					<tbody>
						<ui:param name="objects" value="#{monitorController.objects}"></ui:param>

						<ui:repeat var="obj" value="#{objects}">
							<tr style="#{'OK' eq obj.status?'':'color:red;'}">
								<td>
									<ui:fragment rendered="#{obj.getTarget().startsWith('http')}">
										<a href="#{obj.getTarget()}" target="_blank">#{obj.getTarget()}</a>
									</ui:fragment>
									<ui:fragment rendered="#{!obj.getTarget().startsWith('http')}">
										#{obj.getTarget()}
									</ui:fragment>
								</td>
								<td>#{obj.type}</td>
								<td>#{obj.interval} sec</td>
								<td>#{obj.getPattern()}</td>
								<td>#{obj.status}</td>
								<td>#{obj.lastSuccess}</td>
								<td>#{obj.lastFailure}</td>
							</tr>
						</ui:repeat>
					</tbody>
				</table>

			</div>

		</div>
	</ui:define>
</ui:composition>

src/main/webapp/layout/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:i="http://xmlns.jcp.org/jsf/composite/imixs">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta content="text/javascript" http-equiv="Content-Script-Type" />
	<meta content="text/css" http-equiv="Content-Style-Type" />
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
	<meta content="Imixs Muluk, Web Monitoring" name="keywords" />


	<!-- Auto Refresh -->
	<meta http-equiv="refresh" content="30;" />	
	
	<title>#{message.application_title}</title>

	<!-- Fonts
    ================================================== -->
	<link
		href="#{facesContext.externalContext.requestContextPath}/css/fonts/open_sans.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/css/fonts/typicons.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />



	<!-- Style
    ================================================== -->
	<link
		href="#{facesContext.externalContext.requestContextPath}/css/imixs-basic.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/css/imixs-layout.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />
	<link
		href="#{facesContext.externalContext.requestContextPath}/css/dark/muluk.css"
		charset="UTF-8" type="text/css" rel="stylesheet" />

</h:head>
<h:body>

	<div id="app">

		<f:view>
			<f:loadBundle basename="bundle.message" var="message" />

			<!-- Page Content -->
			<div class="content">
				<div class="container-box header">
					<h1>
						<img src="/css/dark/muluk03.png"
							style="height: 57px; margin-top: 7px; margin-right: 16px; float: left;" />
						Muluk Web Monitor <span style="font-size:1.5rem;float:right;">[#{monitorController.name}]</span>
					</h1>

				</div>

				<ui:insert name="content">
					<h2>Default Content</h2>
				</ui:insert>
			</div>
		</f:view>

		<!-- FOOTER -->
		<div id="imixs-footer"> <a href="/api/config" style="margin-right:20px;">Rest API</a>  <a href="https://github.com/imixs/muluk">Github</a></div>
	</div>
</h:body>
</html>